#!/bin/bash
########################################
domain=$1
########################################
function include(){
        txt=$1
        for host in $(echo $txt | egrep -o "include:(.+) ")
        do
                txt=$(dig $(echo $host | cut -d":" -f2) txt | grep "v=spf1")
                echo $txt;
                if [ "$(echo $txt | grep "include")" ]; then
                        include "$txt"
                fi
        done
}
function main(){
        spf=$(dig ${domain} txt | grep "v=spf1")
        echo $spf

        if [ "$(echo $spf | grep "include")" ]; then
                include "$spf"
        fi
}

main $domain


============================
[root@LY-TEST shell]# ./domain.sh aliyun.com
aliyun.com. 3600 IN TXT "v=spf1 ip4:115.124.30.0/24 ip4:115.124.18.0/26 ip4:115.124.19.0/26 ip4:110.75.46.0/26 \
ip4:110.75.47.0/26 ip4:121.0.18.0/23 ip4:121.0.30.0/24 ip4:110.75.160.0/19 ip4:42.120.70.0/23 ip4:47.88.44.32/27 -all"
